' AWS icon macros. They all accept (e_alias, e_label, e_techn). Prefer including AWSPuml/[CATEGORY]/all.puml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/refs/heads/main/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/Analytics/all.puml
!includeurl AWSPuml/Analytics/Analytics.puml
!includeurl AWSPuml/Analytics/Athena.puml
!includeurl AWSPuml/Analytics/AthenaDataSourceConnectors.puml
!includeurl AWSPuml/Analytics/CleanRooms.puml
!includeurl AWSPuml/Analytics/CloudSearch.puml
!includeurl AWSPuml/Analytics/CloudSearchSearchDocuments.puml
!includeurl AWSPuml/Analytics/DataExchange.puml
!includeurl AWSPuml/Analytics/DataExchangeforAPIs.puml
!includeurl AWSPuml/Analytics/DataFirehose.puml
!includeurl AWSPuml/Analytics/DataPipeline.puml
!includeurl AWSPuml/Analytics/DataZone.puml
!includeurl AWSPuml/Analytics/DataZoneBusinessDataCatalog.puml
!includeurl AWSPuml/Analytics/DataZoneDataPortal.puml
!includeurl AWSPuml/Analytics/DataZoneDataProjects.puml
!includeurl AWSPuml/Analytics/EMR.puml
!includeurl AWSPuml/Analytics/EMRCluster.puml
!includeurl AWSPuml/Analytics/EMREMREngine.puml
!includeurl AWSPuml/Analytics/EMRHDFSCluster.puml
!includeurl AWSPuml/Analytics/EntityResolution.puml
!includeurl AWSPuml/Analytics/FinSpace.puml
!includeurl AWSPuml/Analytics/Glue.puml
!includeurl AWSPuml/Analytics/GlueAWSGlueforRay.puml
!includeurl AWSPuml/Analytics/GlueCrawler.puml
!includeurl AWSPuml/Analytics/GlueDataBrew.puml
!includeurl AWSPuml/Analytics/GlueDataCatalog.puml
!includeurl AWSPuml/Analytics/GlueDataQuality.puml
!includeurl AWSPuml/Analytics/GlueElasticViews.puml
!includeurl AWSPuml/Analytics/Kinesis.puml
!includeurl AWSPuml/Analytics/KinesisDataStreams.puml
!includeurl AWSPuml/Analytics/KinesisVideoStreams.puml
!includeurl AWSPuml/Analytics/LakeFormation.puml
!includeurl AWSPuml/Analytics/LakeFormationDataLake.puml
!includeurl AWSPuml/Analytics/MSKAmazonMSKConnect.puml
!includeurl AWSPuml/Analytics/ManagedServiceforApacheFlink.puml
!includeurl AWSPuml/Analytics/ManagedStreamingforApacheKafka.puml
!includeurl AWSPuml/Analytics/OpenSearchService.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceClusterAdministratorNode.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceDataNode.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceIndex.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceObservability.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceOpenSearchDashboards.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceOpenSearchIngestion.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceTraces.puml
!includeurl AWSPuml/Analytics/OpenSearchServiceUltraWarmNode.puml
!includeurl AWSPuml/Analytics/QuickSight.puml
!includeurl AWSPuml/Analytics/QuicksightPaginatedReports.puml
!includeurl AWSPuml/Analytics/Redshift.puml
!includeurl AWSPuml/Analytics/RedshiftAutocopy.puml
!includeurl AWSPuml/Analytics/RedshiftDataSharingGovernance.puml
!includeurl AWSPuml/Analytics/RedshiftDenseComputeNode.puml
!includeurl AWSPuml/Analytics/RedshiftDenseStorageNode.puml
!includeurl AWSPuml/Analytics/RedshiftML.puml
!includeurl AWSPuml/Analytics/RedshiftQueryEditorv20.puml
!includeurl AWSPuml/Analytics/RedshiftRA3.puml
!includeurl AWSPuml/Analytics/RedshiftStreamingIngestion.puml
!includeurl AWSPuml/ApplicationIntegration/all.puml
!includeurl AWSPuml/ApplicationIntegration/AppFlow.puml
!includeurl AWSPuml/ApplicationIntegration/AppSync.puml
!includeurl AWSPuml/ApplicationIntegration/ApplicationIntegration.puml
!includeurl AWSPuml/ApplicationIntegration/B2BDataInterchange.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridge.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeCustomEventBus.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeDefaultEventBus.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeEvent.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgePipes.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeRule.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeSaasPartnerEvent.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeScheduler.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeSchema.puml
!includeurl AWSPuml/ApplicationIntegration/EventBridgeSchemaRegistry.puml
!includeurl AWSPuml/ApplicationIntegration/ExpressWorkflows.puml
!includeurl AWSPuml/ApplicationIntegration/MQ.puml
!includeurl AWSPuml/ApplicationIntegration/MQBroker.puml
!includeurl AWSPuml/ApplicationIntegration/ManagedWorkflowsforApacheAirflow.puml
!includeurl AWSPuml/ApplicationIntegration/SimpleNotificationService.puml
!includeurl AWSPuml/ApplicationIntegration/SimpleNotificationServiceEmailNotification.puml
!includeurl AWSPuml/ApplicationIntegration/SimpleNotificationServiceHTTPNotification.puml
!includeurl AWSPuml/ApplicationIntegration/SimpleNotificationServiceTopic.puml
!includeurl AWSPuml/ApplicationIntegration/SimpleQueueService.puml
!includeurl AWSPuml/ApplicationIntegration/SimpleQueueServiceMessage.puml
!includeurl AWSPuml/ApplicationIntegration/SimpleQueueServiceQueue.puml
!includeurl AWSPuml/ApplicationIntegration/StepFunctions.puml
!includeurl AWSPuml/ArtificialIntelligence/all.puml
!includeurl AWSPuml/ArtificialIntelligence/ApacheMXNetonAWS.puml
!includeurl AWSPuml/ArtificialIntelligence/ArtificialIntelligence.puml
!includeurl AWSPuml/ArtificialIntelligence/AugmentedAIA2I.puml
!includeurl AWSPuml/ArtificialIntelligence/Bedrock.puml
!includeurl AWSPuml/ArtificialIntelligence/CodeGuru.puml
!includeurl AWSPuml/ArtificialIntelligence/CodeWhisperer.puml
!includeurl AWSPuml/ArtificialIntelligence/Comprehend.puml
!includeurl AWSPuml/ArtificialIntelligence/ComprehendMedical.puml
!includeurl AWSPuml/ArtificialIntelligence/DeepComposer.puml
!includeurl AWSPuml/ArtificialIntelligence/DeepLearningAMIs.puml
!includeurl AWSPuml/ArtificialIntelligence/DeepLearningContainers.puml
!includeurl AWSPuml/ArtificialIntelligence/DeepLens.puml
!includeurl AWSPuml/ArtificialIntelligence/DeepRacer.puml
!includeurl AWSPuml/ArtificialIntelligence/DevOpsGuru.puml
!includeurl AWSPuml/ArtificialIntelligence/DevOpsGuruInsights.puml
!includeurl AWSPuml/ArtificialIntelligence/ElasticInference.puml
!includeurl AWSPuml/ArtificialIntelligence/Forecast.puml
!includeurl AWSPuml/ArtificialIntelligence/FraudDetector.puml
!includeurl AWSPuml/ArtificialIntelligence/HealthImaging.puml
!includeurl AWSPuml/ArtificialIntelligence/HealthLake.puml
!includeurl AWSPuml/ArtificialIntelligence/HealthOmics.puml
!includeurl AWSPuml/ArtificialIntelligence/HealthScribe.puml
!includeurl AWSPuml/ArtificialIntelligence/Kendra.puml
!includeurl AWSPuml/ArtificialIntelligence/Lex.puml
!includeurl AWSPuml/ArtificialIntelligence/LookoutforEquipment.puml
!includeurl AWSPuml/ArtificialIntelligence/LookoutforMetrics.puml
!includeurl AWSPuml/ArtificialIntelligence/LookoutforVision.puml
!includeurl AWSPuml/ArtificialIntelligence/Monitron.puml
!includeurl AWSPuml/ArtificialIntelligence/Neuron.puml
!includeurl AWSPuml/ArtificialIntelligence/Panorama.puml
!includeurl AWSPuml/ArtificialIntelligence/Personalize.puml
!includeurl AWSPuml/ArtificialIntelligence/Polly.puml
!includeurl AWSPuml/ArtificialIntelligence/PyTorchonAWS.puml
!includeurl AWSPuml/ArtificialIntelligence/Q.puml
!includeurl AWSPuml/ArtificialIntelligence/Rekognition.puml
!includeurl AWSPuml/ArtificialIntelligence/RekognitionImage.puml
!includeurl AWSPuml/ArtificialIntelligence/RekognitionVideo.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMaker.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerCanvas.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerGeospatialML.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerGroundTruth.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerModel.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerNotebook.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerShadowTesting.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerStudioLab.puml
!includeurl AWSPuml/ArtificialIntelligence/SageMakerTrain.puml
!includeurl AWSPuml/ArtificialIntelligence/TensorFlowonAWS.puml
!includeurl AWSPuml/ArtificialIntelligence/Textract.puml
!includeurl AWSPuml/ArtificialIntelligence/TextractAnalyzeLending.puml
!includeurl AWSPuml/ArtificialIntelligence/Transcribe.puml
!includeurl AWSPuml/ArtificialIntelligence/Translate.puml
!includeurl AWSPuml/Blockchain/all.puml
!includeurl AWSPuml/Blockchain/Blockchain.puml
!includeurl AWSPuml/Blockchain/ManagedBlockchain.puml
!includeurl AWSPuml/Blockchain/ManagedBlockchainBlockchain.puml
!includeurl AWSPuml/Blockchain/QuantumLedgerDatabase.puml
!includeurl AWSPuml/BusinessApplications/all.puml
!includeurl AWSPuml/BusinessApplications/AlexaForBusiness.puml
!includeurl AWSPuml/BusinessApplications/AppFabric.puml
!includeurl AWSPuml/BusinessApplications/BusinessApplications.puml
!includeurl AWSPuml/BusinessApplications/Chime.puml
!includeurl AWSPuml/BusinessApplications/ChimeSDK.puml
!includeurl AWSPuml/BusinessApplications/Connect.puml
!includeurl AWSPuml/BusinessApplications/Pinpoint.puml
!includeurl AWSPuml/BusinessApplications/PinpointAPIs.puml
!includeurl AWSPuml/BusinessApplications/PinpointJourney.puml
!includeurl AWSPuml/BusinessApplications/SimpleEmailService.puml
!includeurl AWSPuml/BusinessApplications/SimpleEmailServiceEmail.puml
!includeurl AWSPuml/BusinessApplications/SupplyChain.puml
!includeurl AWSPuml/BusinessApplications/Wickr.puml
!includeurl AWSPuml/BusinessApplications/WorkDocs.puml
!includeurl AWSPuml/BusinessApplications/WorkDocsSDK.puml
!includeurl AWSPuml/BusinessApplications/WorkMail.puml
!includeurl AWSPuml/CloudFinancialManagement/all.puml
!includeurl AWSPuml/CloudFinancialManagement/ApplicationCostProfiler.puml
!includeurl AWSPuml/CloudFinancialManagement/BillingConductor.puml
!includeurl AWSPuml/CloudFinancialManagement/Budgets.puml
!includeurl AWSPuml/CloudFinancialManagement/CloudFinancialManagement.puml
!includeurl AWSPuml/CloudFinancialManagement/CostExplorer.puml
!includeurl AWSPuml/CloudFinancialManagement/CostandUsageReport.puml
!includeurl AWSPuml/CloudFinancialManagement/ReservedInstanceReporting.puml
!includeurl AWSPuml/CloudFinancialManagement/SavingsPlans.puml
!includeurl AWSPuml/Compute/all.puml
!includeurl AWSPuml/Compute/AppRunner.puml
!includeurl AWSPuml/Compute/Batch.puml
!includeurl AWSPuml/Compute/Bottlerocket.puml
!includeurl AWSPuml/Compute/Compute.puml
!includeurl AWSPuml/Compute/EC2.puml
!includeurl AWSPuml/Compute/EC2AMI.puml
!includeurl AWSPuml/Compute/EC2AWSMicroserviceExtractorforNET.puml
!includeurl AWSPuml/Compute/EC2AutoScaling.puml
!includeurl AWSPuml/Compute/EC2AutoScalingResource.puml
!includeurl AWSPuml/Compute/EC2DBInstance.puml
!includeurl AWSPuml/Compute/EC2ElasticIPAddress.puml
!includeurl AWSPuml/Compute/EC2ImageBuilder.puml
!includeurl AWSPuml/Compute/EC2Instance.puml
!includeurl AWSPuml/Compute/EC2Instances.puml
!includeurl AWSPuml/Compute/EC2InstancewithCloudWatch.puml
!includeurl AWSPuml/Compute/EC2Rescue.puml
!includeurl AWSPuml/Compute/EC2SpotInstance.puml
!includeurl AWSPuml/Compute/ElasticBeanstalk.puml
!includeurl AWSPuml/Compute/ElasticBeanstalkApplication.puml
!includeurl AWSPuml/Compute/ElasticBeanstalkDeployment.puml
!includeurl AWSPuml/Compute/ElasticFabricAdapter.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Compute/LambdaLambdaFunction.puml
!includeurl AWSPuml/Compute/Lightsail.puml
!includeurl AWSPuml/Compute/LightsailforResearch.puml
!includeurl AWSPuml/Compute/LocalZones.puml
!includeurl AWSPuml/Compute/NICEDCV.puml
!includeurl AWSPuml/Compute/NICEEnginFrame.puml
!includeurl AWSPuml/Compute/NitroEnclaves.puml
!includeurl AWSPuml/Compute/Outpostsfamily.puml
!includeurl AWSPuml/Compute/Outpostsrack.puml
!includeurl AWSPuml/Compute/Outpostsservers.puml
!includeurl AWSPuml/Compute/ParallelCluster.puml
!includeurl AWSPuml/Compute/ServerlessApplicationRepository.puml
!includeurl AWSPuml/Compute/SimSpaceWeaver.puml
!includeurl AWSPuml/Compute/Wavelength.puml
!includeurl AWSPuml/ContactCenter/all.puml
!includeurl AWSPuml/ContactCenter/ContactCenter.puml
!includeurl AWSPuml/Containers/all.puml
!includeurl AWSPuml/Containers/Containers.puml
!includeurl AWSPuml/Containers/ECSAnywhere.puml
!includeurl AWSPuml/Containers/EKSAnywhere.puml
!includeurl AWSPuml/Containers/EKSCloud.puml
!includeurl AWSPuml/Containers/EKSDistro.puml
!includeurl AWSPuml/Containers/ElasticContainerRegistry.puml
!includeurl AWSPuml/Containers/ElasticContainerRegistryImage.puml
!includeurl AWSPuml/Containers/ElasticContainerRegistryRegistry.puml
!includeurl AWSPuml/Containers/ElasticContainerService.puml
!includeurl AWSPuml/Containers/ElasticContainerServiceContainer1.puml
!includeurl AWSPuml/Containers/ElasticContainerServiceContainer2.puml
!includeurl AWSPuml/Containers/ElasticContainerServiceContainer3.puml
!includeurl AWSPuml/Containers/ElasticContainerServiceCopilotCLI.puml
!includeurl AWSPuml/Containers/ElasticContainerServiceECSServiceConnect.puml
!includeurl AWSPuml/Containers/ElasticContainerServiceService.puml
!includeurl AWSPuml/Containers/ElasticContainerServiceTask.puml
!includeurl AWSPuml/Containers/ElasticKubernetesService.puml
!includeurl AWSPuml/Containers/ElasticKubernetesServiceEKSonOutposts.puml
!includeurl AWSPuml/Containers/Fargate.puml
!includeurl AWSPuml/Containers/RedHatOpenShiftServiceonAWS.puml
!includeurl AWSPuml/CustomerEnablement/all.puml
!includeurl AWSPuml/CustomerEnablement/Activate.puml
!includeurl AWSPuml/CustomerEnablement/CustomerEnablement.puml
!includeurl AWSPuml/CustomerEnablement/IQ.puml
!includeurl AWSPuml/CustomerEnablement/ManagedServices.puml
!includeurl AWSPuml/CustomerEnablement/ProfessionalServices.puml
!includeurl AWSPuml/CustomerEnablement/Support.puml
!includeurl AWSPuml/CustomerEnablement/TrainingCertification.puml
!includeurl AWSPuml/CustomerEnablement/rePost.puml
!includeurl AWSPuml/CustomerEnablement/rePostPrivate.puml
!includeurl AWSPuml/Database/all.puml
!includeurl AWSPuml/Database/Aurora.puml
!includeurl AWSPuml/Database/AuroraAmazonAuroraInstanceAlternate.puml
!includeurl AWSPuml/Database/AuroraAmazonRDSInstance.puml
!includeurl AWSPuml/Database/AuroraAmazonRDSInstanceAlternate.puml
!includeurl AWSPuml/Database/AuroraInstance.puml
!includeurl AWSPuml/Database/AuroraMariaDBInstance.puml
!includeurl AWSPuml/Database/AuroraMariaDBInstanceAlternate.puml
!includeurl AWSPuml/Database/AuroraMySQLInstance.puml
!includeurl AWSPuml/Database/AuroraMySQLInstanceAlternate.puml
!includeurl AWSPuml/Database/AuroraOracleInstance.puml
!includeurl AWSPuml/Database/AuroraOracleInstanceAlternate.puml
!includeurl AWSPuml/Database/AuroraPIOPSInstance.puml
!includeurl AWSPuml/Database/AuroraPostgreSQLInstance.puml
!includeurl AWSPuml/Database/AuroraPostgreSQLInstanceAlternate.puml
!includeurl AWSPuml/Database/AuroraSQLServerInstance.puml
!includeurl AWSPuml/Database/AuroraSQLServerInstanceAlternate.puml
!includeurl AWSPuml/Database/AuroraTrustedLanguageExtensionsforPostgreSQL.puml
!includeurl AWSPuml/Database/Database.puml
!includeurl AWSPuml/Database/DatabaseMigrationService.puml
!includeurl AWSPuml/Database/DatabaseMigrationServiceDatabasemigrationworkflowjob.puml
!includeurl AWSPuml/Database/DocumentDB.puml
!includeurl AWSPuml/Database/DocumentDBElasticClusters.puml
!includeurl AWSPuml/Database/DynamoDB.puml
!includeurl AWSPuml/Database/DynamoDBAmazonDynamoDBAccelerator.puml
!includeurl AWSPuml/Database/DynamoDBAttribute.puml
!includeurl AWSPuml/Database/DynamoDBAttributes.puml
!includeurl AWSPuml/Database/DynamoDBGlobalsecondaryindex.puml
!includeurl AWSPuml/Database/DynamoDBItem.puml
!includeurl AWSPuml/Database/DynamoDBItems.puml
!includeurl AWSPuml/Database/DynamoDBStandardAccessTableClass.puml
!includeurl AWSPuml/Database/DynamoDBStandardInfrequentAccessTableClass.puml
!includeurl AWSPuml/Database/DynamoDBStream.puml
!includeurl AWSPuml/Database/DynamoDBTable.puml
!includeurl AWSPuml/Database/ElastiCache.puml
!includeurl AWSPuml/Database/ElastiCacheCacheNode.puml
!includeurl AWSPuml/Database/ElastiCacheElastiCacheforMemcached.puml
!includeurl AWSPuml/Database/ElastiCacheElastiCacheforRedis.puml
!includeurl AWSPuml/Database/Keyspaces.puml
!includeurl AWSPuml/Database/MemoryDBforRedis.puml
!includeurl AWSPuml/Database/Neptune.puml
!includeurl AWSPuml/Database/RDS.puml
!includeurl AWSPuml/Database/RDSBlueGreenDeployments.puml
!includeurl AWSPuml/Database/RDSMultiAZ.puml
!includeurl AWSPuml/Database/RDSMultiAZDBCluster.puml
!includeurl AWSPuml/Database/RDSOptimizedWrites.puml
!includeurl AWSPuml/Database/RDSProxyInstance.puml
!includeurl AWSPuml/Database/RDSProxyInstanceAlternate.puml
!includeurl AWSPuml/Database/RDSTrustedLanguageExtensionsforPostgreSQL.puml
!includeurl AWSPuml/Database/RDSonVMware.puml
!includeurl AWSPuml/Database/Timestream.puml
!includeurl AWSPuml/DeveloperTools/all.puml
!includeurl AWSPuml/DeveloperTools/ApplicationComposer.puml
!includeurl AWSPuml/DeveloperTools/Cloud9.puml
!includeurl AWSPuml/DeveloperTools/Cloud9Cloud9.puml
!includeurl AWSPuml/DeveloperTools/CloudControlAPI.puml
!includeurl AWSPuml/DeveloperTools/CloudDevelopmentKit.puml
!includeurl AWSPuml/DeveloperTools/CloudShell.puml
!includeurl AWSPuml/DeveloperTools/CodeArtifact.puml
!includeurl AWSPuml/DeveloperTools/CodeBuild.puml
!includeurl AWSPuml/DeveloperTools/CodeCatalyst.puml
!includeurl AWSPuml/DeveloperTools/CodeCommit.puml
!includeurl AWSPuml/DeveloperTools/CodeDeploy.puml
!includeurl AWSPuml/DeveloperTools/CodePipeline.puml
!includeurl AWSPuml/DeveloperTools/CodeStar.puml
!includeurl AWSPuml/DeveloperTools/CommandLineInterface.puml
!includeurl AWSPuml/DeveloperTools/Corretto.puml
!includeurl AWSPuml/DeveloperTools/DeveloperTools.puml
!includeurl AWSPuml/DeveloperTools/FaultInjectionService.puml
!includeurl AWSPuml/DeveloperTools/ToolsandSDKs.puml
!includeurl AWSPuml/DeveloperTools/XRay.puml
!includeurl AWSPuml/EndUserComputing/all.puml
!includeurl AWSPuml/EndUserComputing/AppStream2.puml
!includeurl AWSPuml/EndUserComputing/EndUserComputing.puml
!includeurl AWSPuml/EndUserComputing/WorkSpacesFamily.puml
!includeurl AWSPuml/EndUserComputing/WorkSpacesFamilyAmazonWorkSpaces.puml
!includeurl AWSPuml/EndUserComputing/WorkSpacesFamilyAmazonWorkSpacesCore.puml
!includeurl AWSPuml/EndUserComputing/WorkSpacesFamilyAmazonWorkSpacesSecureBrowser.puml
!includeurl AWSPuml/EndUserComputing/WorkSpacesThinClient.puml
!includeurl AWSPuml/FrontEndWebMobile/all.puml
!includeurl AWSPuml/FrontEndWebMobile/Amplify.puml
!includeurl AWSPuml/FrontEndWebMobile/AmplifyAWSAmplifyStudio.puml
!includeurl AWSPuml/FrontEndWebMobile/DeviceFarm.puml
!includeurl AWSPuml/FrontEndWebMobile/FrontEndWebMobile.puml
!includeurl AWSPuml/FrontEndWebMobile/LocationService.puml
!includeurl AWSPuml/FrontEndWebMobile/LocationServiceGeofence.puml
!includeurl AWSPuml/FrontEndWebMobile/LocationServiceMap.puml
!includeurl AWSPuml/FrontEndWebMobile/LocationServicePlace.puml
!includeurl AWSPuml/FrontEndWebMobile/LocationServiceRoutes.puml
!includeurl AWSPuml/FrontEndWebMobile/LocationServiceTrack.puml
!includeurl AWSPuml/Games/all.puml
!includeurl AWSPuml/Games/GameKit.puml
!includeurl AWSPuml/Games/GameLift.puml
!includeurl AWSPuml/Games/GameSparks.puml
!includeurl AWSPuml/Games/Games.puml
!includeurl AWSPuml/Games/Open3DEngine.puml
!includeurl AWSPuml/General/all.puml
!includeurl AWSPuml/General/AWSManagementConsole.puml
!includeurl AWSPuml/General/Alert.puml
!includeurl AWSPuml/General/AuthenticatedUser.puml
!includeurl AWSPuml/General/Camera.puml
!includeurl AWSPuml/General/Chat.puml
!includeurl AWSPuml/General/Client.puml
!includeurl AWSPuml/General/ColdStorage.puml
!includeurl AWSPuml/General/Credentials.puml
!includeurl AWSPuml/General/DataStream.puml
!includeurl AWSPuml/General/DataTable.puml
!includeurl AWSPuml/General/Disk.puml
!includeurl AWSPuml/General/Document.puml
!includeurl AWSPuml/General/Documents.puml
!includeurl AWSPuml/General/Email.puml
!includeurl AWSPuml/General/Firewall.puml
!includeurl AWSPuml/General/Folder.puml
!includeurl AWSPuml/General/Folders.puml
!includeurl AWSPuml/General/Forums.puml
!includeurl AWSPuml/General/Gear.puml
!includeurl AWSPuml/General/GenericApplication.puml
!includeurl AWSPuml/General/Genericdatabase.puml
!includeurl AWSPuml/General/GitRepository.puml
!includeurl AWSPuml/General/Globe.puml
!includeurl AWSPuml/General/Internet.puml
!includeurl AWSPuml/General/Internetalt1.puml
!includeurl AWSPuml/General/Internetalt2.puml
!includeurl AWSPuml/General/JSONScript.puml
!includeurl AWSPuml/General/Logs.puml
!includeurl AWSPuml/General/MagnifyingGlass.puml
!includeurl AWSPuml/General/Marketplace.puml
!includeurl AWSPuml/General/Metrics.puml
!includeurl AWSPuml/General/Mobileclient.puml
!includeurl AWSPuml/General/Multimedia.puml
!includeurl AWSPuml/General/Officebuilding.puml
!includeurl AWSPuml/General/ProgrammingLanguage.puml
!includeurl AWSPuml/General/Question.puml
!includeurl AWSPuml/General/Recover.puml
!includeurl AWSPuml/General/SAMLtoken.puml
!includeurl AWSPuml/General/SDK.puml
!includeurl AWSPuml/General/SSLpadlock.puml
!includeurl AWSPuml/General/Servers.puml
!includeurl AWSPuml/General/Shield2.puml
!includeurl AWSPuml/General/SourceCode.puml
!includeurl AWSPuml/General/Tapestorage.puml
!includeurl AWSPuml/General/Toolkit.puml
!includeurl AWSPuml/General/Traditionalserver.puml
!includeurl AWSPuml/General/User.puml
!includeurl AWSPuml/General/Users.puml
!includeurl AWSPuml/Groups/all.puml
!includeurl AWSPuml/Groups/AWSAccount.puml
!includeurl AWSPuml/Groups/AWSCloud.puml
!includeurl AWSPuml/Groups/AWSCloudAlt.puml
!includeurl AWSPuml/Groups/AutoScalingGroup.puml
!includeurl AWSPuml/Groups/AvailabilityZone.puml
!includeurl AWSPuml/Groups/CorporateDataCenter.puml
!includeurl AWSPuml/Groups/EC2InstanceContents.puml
!includeurl AWSPuml/Groups/ElasticBeanstalkContainer.puml
!includeurl AWSPuml/Groups/Generic.puml
!includeurl AWSPuml/Groups/GenericAlt.puml
!includeurl AWSPuml/Groups/GenericBlue.puml
!includeurl AWSPuml/Groups/GenericGreen.puml
!includeurl AWSPuml/Groups/GenericOrange.puml
!includeurl AWSPuml/Groups/GenericPink.puml
!includeurl AWSPuml/Groups/GenericPurple.puml
!includeurl AWSPuml/Groups/GenericRed.puml
!includeurl AWSPuml/Groups/GenericTurquoise.puml
!includeurl AWSPuml/Groups/IoTGreengrass.puml
!includeurl AWSPuml/Groups/IoTGreengrassDeployment.puml
!includeurl AWSPuml/Groups/PrivateSubnet.puml
!includeurl AWSPuml/Groups/PublicSubnet.puml
!includeurl AWSPuml/Groups/Region.puml
!includeurl AWSPuml/Groups/SecurityGroup.puml
!includeurl AWSPuml/Groups/ServerContents.puml
!includeurl AWSPuml/Groups/SpotFleet.puml
!includeurl AWSPuml/Groups/StepFunctionsWorkflow.puml
!includeurl AWSPuml/Groups/VPC.puml
!includeurl AWSPuml/InternetOfThings/all.puml
!includeurl AWSPuml/InternetOfThings/FreeRTOS.puml
!includeurl AWSPuml/InternetOfThings/InternetOfThings.puml
!includeurl AWSPuml/InternetOfThings/IoT1Click.puml
!includeurl AWSPuml/InternetOfThings/IoTAction.puml
!includeurl AWSPuml/InternetOfThings/IoTActuator.puml
!includeurl AWSPuml/InternetOfThings/IoTAlexaEnabledDevice.puml
!includeurl AWSPuml/InternetOfThings/IoTAlexaSkill.puml
!includeurl AWSPuml/InternetOfThings/IoTAlexaVoiceService.puml
!includeurl AWSPuml/InternetOfThings/IoTAnalytics.puml
!includeurl AWSPuml/InternetOfThings/IoTAnalyticsChannel.puml
!includeurl AWSPuml/InternetOfThings/IoTAnalyticsDataStore.puml
!includeurl AWSPuml/InternetOfThings/IoTAnalyticsDataset.puml
!includeurl AWSPuml/InternetOfThings/IoTAnalyticsNotebook.puml
!includeurl AWSPuml/InternetOfThings/IoTAnalyticsPipeline.puml
!includeurl AWSPuml/InternetOfThings/IoTButton.puml
!includeurl AWSPuml/InternetOfThings/IoTCertificate.puml
!includeurl AWSPuml/InternetOfThings/IoTCore.puml
!includeurl AWSPuml/InternetOfThings/IoTCoreDeviceAdvisor.puml
!includeurl AWSPuml/InternetOfThings/IoTCoreDeviceLocation.puml
!includeurl AWSPuml/InternetOfThings/IoTDesiredState.puml
!includeurl AWSPuml/InternetOfThings/IoTDeviceDefender.puml
!includeurl AWSPuml/InternetOfThings/IoTDeviceDefenderIoTDeviceJobs.puml
!includeurl AWSPuml/InternetOfThings/IoTDeviceGateway.puml
!includeurl AWSPuml/InternetOfThings/IoTDeviceManagement.puml
!includeurl AWSPuml/InternetOfThings/IoTDeviceManagementFleetHub.puml
!includeurl AWSPuml/InternetOfThings/IoTDeviceTester.puml
!includeurl AWSPuml/InternetOfThings/IoTEcho.puml
!includeurl AWSPuml/InternetOfThings/IoTEvents.puml
!includeurl AWSPuml/InternetOfThings/IoTExpressLink.puml
!includeurl AWSPuml/InternetOfThings/IoTFireTV.puml
!includeurl AWSPuml/InternetOfThings/IoTFireTVStick.puml
!includeurl AWSPuml/InternetOfThings/IoTFleetWise.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrass.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassArtifact.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassComponent.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassComponentMachineLearning.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassComponentNucleus.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassComponentPrivate.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassComponentPublic.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassConnector.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassInterprocessCommunication.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassProtocol.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassRecipe.puml
!includeurl AWSPuml/InternetOfThings/IoTGreengrassStreamManager.puml
!includeurl AWSPuml/InternetOfThings/IoTHTTP2Protocol.puml
!includeurl AWSPuml/InternetOfThings/IoTHTTPProtocol.puml
!includeurl AWSPuml/InternetOfThings/IoTHardwareBoard.puml
!includeurl AWSPuml/InternetOfThings/IoTLambdaFunction.puml
!includeurl AWSPuml/InternetOfThings/IoTLoRaWANProtocol.puml
!includeurl AWSPuml/InternetOfThings/IoTMQTTProtocol.puml
!includeurl AWSPuml/InternetOfThings/IoTOverAirUpdate.puml
!includeurl AWSPuml/InternetOfThings/IoTPolicy.puml
!includeurl AWSPuml/InternetOfThings/IoTReportedState.puml
!includeurl AWSPuml/InternetOfThings/IoTRoboRunner.puml
!includeurl AWSPuml/InternetOfThings/IoTRule.puml
!includeurl AWSPuml/InternetOfThings/IoTSailboat.puml
!includeurl AWSPuml/InternetOfThings/IoTSensor.puml
!includeurl AWSPuml/InternetOfThings/IoTServo.puml
!includeurl AWSPuml/InternetOfThings/IoTShadow.puml
!includeurl AWSPuml/InternetOfThings/IoTSimulator.puml
!includeurl AWSPuml/InternetOfThings/IoTSiteWise.puml
!includeurl AWSPuml/InternetOfThings/IoTSiteWiseAsset.puml
!includeurl AWSPuml/InternetOfThings/IoTSiteWiseAssetHierarchy.puml
!includeurl AWSPuml/InternetOfThings/IoTSiteWiseAssetModel.puml
!includeurl AWSPuml/InternetOfThings/IoTSiteWiseAssetProperties.puml
!includeurl AWSPuml/InternetOfThings/IoTSiteWiseDataStreams.puml
!includeurl AWSPuml/InternetOfThings/IoTThingBank.puml
!includeurl AWSPuml/InternetOfThings/IoTThingBicycle.puml
!includeurl AWSPuml/InternetOfThings/IoTThingCamera.puml
!includeurl AWSPuml/InternetOfThings/IoTThingCar.puml
!includeurl AWSPuml/InternetOfThings/IoTThingCart.puml
!includeurl AWSPuml/InternetOfThings/IoTThingCoffeePot.puml
!includeurl AWSPuml/InternetOfThings/IoTThingDoorLock.puml
!includeurl AWSPuml/InternetOfThings/IoTThingFactory.puml
!includeurl AWSPuml/InternetOfThings/IoTThingFreeRTOSDevice.puml
!includeurl AWSPuml/InternetOfThings/IoTThingGeneric.puml
!includeurl AWSPuml/InternetOfThings/IoTThingHouse.puml
!includeurl AWSPuml/InternetOfThings/IoTThingHumiditySensor.puml
!includeurl AWSPuml/InternetOfThings/IoTThingIndustrialPC.puml
!includeurl AWSPuml/InternetOfThings/IoTThingLightbulb.puml
!includeurl AWSPuml/InternetOfThings/IoTThingMedicalEmergency.puml
!includeurl AWSPuml/InternetOfThings/IoTThingPLC.puml
!includeurl AWSPuml/InternetOfThings/IoTThingPoliceEmergency.puml
!includeurl AWSPuml/InternetOfThings/IoTThingRelay.puml
!includeurl AWSPuml/InternetOfThings/IoTThingStacklight.puml
!includeurl AWSPuml/InternetOfThings/IoTThingTemperatureHumiditySensor.puml
!includeurl AWSPuml/InternetOfThings/IoTThingTemperatureSensor.puml
!includeurl AWSPuml/InternetOfThings/IoTThingTemperatureVibrationSensor.puml
!includeurl AWSPuml/InternetOfThings/IoTThingThermostat.puml
!includeurl AWSPuml/InternetOfThings/IoTThingTravel.puml
!includeurl AWSPuml/InternetOfThings/IoTThingUtility.puml
!includeurl AWSPuml/InternetOfThings/IoTThingVibrationSensor.puml
!includeurl AWSPuml/InternetOfThings/IoTThingWindfarm.puml
!includeurl AWSPuml/InternetOfThings/IoTTopic.puml
!includeurl AWSPuml/InternetOfThings/IoTTwinMaker.puml
!includeurl AWSPuml/ManagementGovernance/all.puml
!includeurl AWSPuml/ManagementGovernance/AppConfig.puml
!includeurl AWSPuml/ManagementGovernance/ApplicationAutoScaling2.puml
!includeurl AWSPuml/ManagementGovernance/AutoScaling.puml
!includeurl AWSPuml/ManagementGovernance/BackintAgent.puml
!includeurl AWSPuml/ManagementGovernance/Chatbot.puml
!includeurl AWSPuml/ManagementGovernance/CloudFormation.puml
!includeurl AWSPuml/ManagementGovernance/CloudFormationChangeSet.puml
!includeurl AWSPuml/ManagementGovernance/CloudFormationStack.puml
!includeurl AWSPuml/ManagementGovernance/CloudFormationTemplate.puml
!includeurl AWSPuml/ManagementGovernance/CloudTrail.puml
!includeurl AWSPuml/ManagementGovernance/CloudTrailCloudTrailLake.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatch.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchAlarm.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchCrossaccountObservability.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchDataProtection.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchEventEventBased.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchEventTimeBased.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchEvidently.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchLogs.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchMetricsInsights.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchRUM.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchRule.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatchSynthetics.puml
!includeurl AWSPuml/ManagementGovernance/ComputeOptimizer.puml
!includeurl AWSPuml/ManagementGovernance/Config.puml
!includeurl AWSPuml/ManagementGovernance/ConsoleMobileApplication.puml
!includeurl AWSPuml/ManagementGovernance/ControlTower.puml
!includeurl AWSPuml/ManagementGovernance/DistroforOpenTelemetry.puml
!includeurl AWSPuml/ManagementGovernance/HealthDashboard.puml
!includeurl AWSPuml/ManagementGovernance/LaunchWizard.puml
!includeurl AWSPuml/ManagementGovernance/LicenseManager.puml
!includeurl AWSPuml/ManagementGovernance/LicenseManagerApplicationDiscovery.puml
!includeurl AWSPuml/ManagementGovernance/LicenseManagerLicenseBlending.puml
!includeurl AWSPuml/ManagementGovernance/ManagedGrafana.puml
!includeurl AWSPuml/ManagementGovernance/ManagedServiceforPrometheus.puml
!includeurl AWSPuml/ManagementGovernance/ManagementConsole.puml
!includeurl AWSPuml/ManagementGovernance/ManagementGovernance.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorks.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksApps.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksDeployments.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksInstances.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksLayers.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksMonitoring.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksPermissions.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksResources.puml
!includeurl AWSPuml/ManagementGovernance/OpsWorksStack2.puml
!includeurl AWSPuml/ManagementGovernance/Organizations.puml
!includeurl AWSPuml/ManagementGovernance/OrganizationsAccount.puml
!includeurl AWSPuml/ManagementGovernance/OrganizationsManagementAccount.puml
!includeurl AWSPuml/ManagementGovernance/OrganizationsOrganizationalUnit.puml
!includeurl AWSPuml/ManagementGovernance/Proton.puml
!includeurl AWSPuml/ManagementGovernance/ResilienceHub.puml
!includeurl AWSPuml/ManagementGovernance/ResourceExplorer.puml
!includeurl AWSPuml/ManagementGovernance/ServiceCatalog.puml
!includeurl AWSPuml/ManagementGovernance/ServiceManagementConnector.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManager.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerApplicationManager.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerAutomation.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerChangeCalendar.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerChangeManager.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerCompliance.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerDistributor.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerDocuments.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerIncidentManager.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerInventory.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerMaintenanceWindows.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerOpsCenter.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerParameterStore.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerPatchManager.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerRunCommand.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerSessionManager.puml
!includeurl AWSPuml/ManagementGovernance/SystemsManagerStateManager.puml
!includeurl AWSPuml/ManagementGovernance/TelcoNetworkBuilder.puml
!includeurl AWSPuml/ManagementGovernance/TrustedAdvisor.puml
!includeurl AWSPuml/ManagementGovernance/TrustedAdvisorChecklist.puml
!includeurl AWSPuml/ManagementGovernance/TrustedAdvisorChecklistCost.puml
!includeurl AWSPuml/ManagementGovernance/TrustedAdvisorChecklistFaultTolerant.puml
!includeurl AWSPuml/ManagementGovernance/TrustedAdvisorChecklistPerformance.puml
!includeurl AWSPuml/ManagementGovernance/TrustedAdvisorChecklistSecurity.puml
!includeurl AWSPuml/ManagementGovernance/WellArchitectedTool.puml
!includeurl AWSPuml/MediaServices/all.puml
!includeurl AWSPuml/MediaServices/CloudDigitalInterface.puml
!includeurl AWSPuml/MediaServices/DeadlineCloud.puml
!includeurl AWSPuml/MediaServices/ElasticTranscoder.puml
!includeurl AWSPuml/MediaServices/ElementalAppliancesSoftware.puml
!includeurl AWSPuml/MediaServices/ElementalConductor.puml
!includeurl AWSPuml/MediaServices/ElementalDelta.puml
!includeurl AWSPuml/MediaServices/ElementalLink.puml
!includeurl AWSPuml/MediaServices/ElementalLive.puml
!includeurl AWSPuml/MediaServices/ElementalMediaConnect.puml
!includeurl AWSPuml/MediaServices/ElementalMediaConnectMediaConnectGateway.puml
!includeurl AWSPuml/MediaServices/ElementalMediaConvert.puml
!includeurl AWSPuml/MediaServices/ElementalMediaLive.puml
!includeurl AWSPuml/MediaServices/ElementalMediaPackage.puml
!includeurl AWSPuml/MediaServices/ElementalMediaStore.puml
!includeurl AWSPuml/MediaServices/ElementalMediaTailor.puml
!includeurl AWSPuml/MediaServices/ElementalServer.puml
!includeurl AWSPuml/MediaServices/InteractiveVideoService.puml
!includeurl AWSPuml/MediaServices/KinesisVideoStreams2.puml
!includeurl AWSPuml/MediaServices/MediaServices.puml
!includeurl AWSPuml/MediaServices/NimbleStudio.puml
!includeurl AWSPuml/MediaServices/ThinkboxDeadline.puml
!includeurl AWSPuml/MediaServices/ThinkboxFrost.puml
!includeurl AWSPuml/MediaServices/ThinkboxKrakatoa.puml
!includeurl AWSPuml/MediaServices/ThinkboxStoke.puml
!includeurl AWSPuml/MediaServices/ThinkboxXMesh.puml
!includeurl AWSPuml/MigrationModernization/all.puml
!includeurl AWSPuml/MigrationModernization/ApplicationDiscoveryService.puml
!includeurl AWSPuml/MigrationModernization/ApplicationDiscoveryServiceAWSAgentlessCollector.puml
!includeurl AWSPuml/MigrationModernization/ApplicationDiscoveryServiceAWSDiscoveryAgent.puml
!includeurl AWSPuml/MigrationModernization/ApplicationDiscoveryServiceMigrationEvaluatorCollector.puml
!includeurl AWSPuml/MigrationModernization/ApplicationMigrationService.puml
!includeurl AWSPuml/MigrationModernization/DataSync.puml
!includeurl AWSPuml/MigrationModernization/DataSyncDiscovery.puml
!includeurl AWSPuml/MigrationModernization/DatasyncAgent.puml
!includeurl AWSPuml/MigrationModernization/MainframeModernization.puml
!includeurl AWSPuml/MigrationModernization/MainframeModernizationAnalyzer.puml
!includeurl AWSPuml/MigrationModernization/MainframeModernizationCompiler.puml
!includeurl AWSPuml/MigrationModernization/MainframeModernizationConverter.puml
!includeurl AWSPuml/MigrationModernization/MainframeModernizationDeveloper.puml
!includeurl AWSPuml/MigrationModernization/MainframeModernizationRuntime.puml
!includeurl AWSPuml/MigrationModernization/MigrationEvaluator.puml
!includeurl AWSPuml/MigrationModernization/MigrationHub.puml
!includeurl AWSPuml/MigrationModernization/MigrationHubRefactorSpacesApplications.puml
!includeurl AWSPuml/MigrationModernization/MigrationHubRefactorSpacesEnvironments.puml
!includeurl AWSPuml/MigrationModernization/MigrationHubRefactorSpacesServices.puml
!includeurl AWSPuml/MigrationModernization/MigrationModernization.puml
!includeurl AWSPuml/MigrationModernization/TransferFamily.puml
!includeurl AWSPuml/MigrationModernization/TransferFamilyAWSAS2.puml
!includeurl AWSPuml/MigrationModernization/TransferFamilyAWSFTP.puml
!includeurl AWSPuml/MigrationModernization/TransferFamilyAWSFTPS.puml
!includeurl AWSPuml/MigrationModernization/TransferFamilyAWSSFTP.puml
!includeurl AWSPuml/NetworkingContentDelivery/all.puml
!includeurl AWSPuml/NetworkingContentDelivery/APIGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/APIGatewayEndpoint.puml
!includeurl AWSPuml/NetworkingContentDelivery/AppMesh.puml
!includeurl AWSPuml/NetworkingContentDelivery/AppMeshMesh.puml
!includeurl AWSPuml/NetworkingContentDelivery/AppMeshVirtualGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/AppMeshVirtualNode.puml
!includeurl AWSPuml/NetworkingContentDelivery/AppMeshVirtualRouter.puml
!includeurl AWSPuml/NetworkingContentDelivery/AppMeshVirtualService.puml
!includeurl AWSPuml/NetworkingContentDelivery/ClientVPN.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudFront.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudFrontDownloadDistribution.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudFrontEdgeLocation.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudFrontFunctions.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudFrontStreamingDistribution.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudMap.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudMapNamespace.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudMapResource.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudMapService.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudWAN.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudWANCoreNetworkEdge.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudWANSegmentNetwork.puml
!includeurl AWSPuml/NetworkingContentDelivery/CloudWANTransitGatewayRouteTableAttachment.puml
!includeurl AWSPuml/NetworkingContentDelivery/DirectConnect.puml
!includeurl AWSPuml/NetworkingContentDelivery/DirectConnectGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/ElasticLoadBalancing.puml
!includeurl AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingApplicationLoadBalancer.puml
!includeurl AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingClassicLoadBalancer.puml
!includeurl AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingGatewayLoadBalancer.puml
!includeurl AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingNetworkLoadBalancer.puml
!includeurl AWSPuml/NetworkingContentDelivery/GlobalAccelerator.puml
!includeurl AWSPuml/NetworkingContentDelivery/NetworkingContentDelivery.puml
!includeurl AWSPuml/NetworkingContentDelivery/Private5G.puml
!includeurl AWSPuml/NetworkingContentDelivery/PrivateLink.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53ApplicationRecoveryController.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53HostedZone.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53ReadinessChecks.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53Resolver.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53ResolverDNSFirewall.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53ResolverQueryLogging.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53RouteTable.puml
!includeurl AWSPuml/NetworkingContentDelivery/Route53RoutingControls.puml
!includeurl AWSPuml/NetworkingContentDelivery/SitetoSiteVPN.puml
!includeurl AWSPuml/NetworkingContentDelivery/TransitGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/TransitGatewayAttachment.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCCarrierGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCCustomerGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCElasticNetworkAdapter.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCElasticNetworkInterface.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCEndpoints.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCFlowLogs.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCLattice.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCNATGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCNetworkAccessAnalyzer.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCNetworkAccessControlList.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCPeeringConnection.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCReachabilityAnalyzer.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCRouter.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCTrafficMirroring.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCVPNConnection.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCVPNGateway.puml
!includeurl AWSPuml/NetworkingContentDelivery/VPCVirtualprivatecloudVPC.puml
!includeurl AWSPuml/NetworkingContentDelivery/VerifiedAccess.puml
!includeurl AWSPuml/NetworkingContentDelivery/VirtualPrivateCloud.puml
!includeurl AWSPuml/QuantumTechnologies/all.puml
!includeurl AWSPuml/QuantumTechnologies/Braket.puml
!includeurl AWSPuml/QuantumTechnologies/BraketChandelier.puml
!includeurl AWSPuml/QuantumTechnologies/BraketChip.puml
!includeurl AWSPuml/QuantumTechnologies/BraketEmbeddedSimulator.puml
!includeurl AWSPuml/QuantumTechnologies/BraketManagedSimulator.puml
!includeurl AWSPuml/QuantumTechnologies/BraketNoiseSimulator.puml
!includeurl AWSPuml/QuantumTechnologies/BraketQPU.puml
!includeurl AWSPuml/QuantumTechnologies/BraketSimulator.puml
!includeurl AWSPuml/QuantumTechnologies/BraketSimulator1.puml
!includeurl AWSPuml/QuantumTechnologies/BraketSimulator2.puml
!includeurl AWSPuml/QuantumTechnologies/BraketSimulator3.puml
!includeurl AWSPuml/QuantumTechnologies/BraketSimulator4.puml
!includeurl AWSPuml/QuantumTechnologies/BraketStateVector.puml
!includeurl AWSPuml/QuantumTechnologies/BraketTensorNetwork.puml
!includeurl AWSPuml/QuantumTechnologies/QuantumTechnologies.puml
!includeurl AWSPuml/Robotics/all.puml
!includeurl AWSPuml/Robotics/RoboMaker.puml
!includeurl AWSPuml/Robotics/RoboMakerCloudExtensionsROS.puml
!includeurl AWSPuml/Robotics/RoboMakerDevelopmentEnvironment.puml
!includeurl AWSPuml/Robotics/RoboMakerFleetManagement.puml
!includeurl AWSPuml/Robotics/RoboMakerSimulation.puml
!includeurl AWSPuml/Robotics/Robotics.puml
!includeurl AWSPuml/Satellite/all.puml
!includeurl AWSPuml/Satellite/GroundStation.puml
!includeurl AWSPuml/Satellite/Satellite.puml
!includeurl AWSPuml/SecurityIdentityCompliance/all.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Artifact.puml
!includeurl AWSPuml/SecurityIdentityCompliance/AuditManager.puml
!includeurl AWSPuml/SecurityIdentityCompliance/CertificateManager.puml
!includeurl AWSPuml/SecurityIdentityCompliance/CertificateManagerCertificateAuthority.puml
!includeurl AWSPuml/SecurityIdentityCompliance/CloudDirectory.puml
!includeurl AWSPuml/SecurityIdentityCompliance/CloudHSM.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Cognito.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Detective.puml
!includeurl AWSPuml/SecurityIdentityCompliance/DirectoryService.puml
!includeurl AWSPuml/SecurityIdentityCompliance/DirectoryServiceADConnector.puml
!includeurl AWSPuml/SecurityIdentityCompliance/DirectoryServiceAWSManagedMicrosoftAD.puml
!includeurl AWSPuml/SecurityIdentityCompliance/DirectoryServiceSimpleAD.puml
!includeurl AWSPuml/SecurityIdentityCompliance/FirewallManager.puml
!includeurl AWSPuml/SecurityIdentityCompliance/GuardDuty.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IAMIdentityCenter.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementAWSSTS.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementAWSSTSAlternate.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementAddon.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementDataEncryptionKey.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementEncryptedData.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementIAMAccessAnalyzer.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementIAMRolesAnywhere.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementLongTermSecurityCredential.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementMFAToken.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementPermissions.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementRole.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityAccessManagementTemporarySecurityCredential.puml
!includeurl AWSPuml/SecurityIdentityCompliance/IdentityandAccessManagement.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Inspector.puml
!includeurl AWSPuml/SecurityIdentityCompliance/InspectorAgent.puml
!includeurl AWSPuml/SecurityIdentityCompliance/KeyManagementService.puml
!includeurl AWSPuml/SecurityIdentityCompliance/KeyManagementServiceExternalKeyStore.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Macie.puml
!includeurl AWSPuml/SecurityIdentityCompliance/NetworkFirewall.puml
!includeurl AWSPuml/SecurityIdentityCompliance/NetworkFirewallEndpoints.puml
!includeurl AWSPuml/SecurityIdentityCompliance/PaymentCryptography.puml
!includeurl AWSPuml/SecurityIdentityCompliance/PrivateCertificateAuthority.puml
!includeurl AWSPuml/SecurityIdentityCompliance/ResourceAccessManager.puml
!includeurl AWSPuml/SecurityIdentityCompliance/SecretsManager.puml
!includeurl AWSPuml/SecurityIdentityCompliance/SecurityHub.puml
!includeurl AWSPuml/SecurityIdentityCompliance/SecurityHubFinding.puml
!includeurl AWSPuml/SecurityIdentityCompliance/SecurityIdentityCompliance.puml
!includeurl AWSPuml/SecurityIdentityCompliance/SecurityLake.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Shield.puml
!includeurl AWSPuml/SecurityIdentityCompliance/ShieldAWSShieldAdvanced.puml
!includeurl AWSPuml/SecurityIdentityCompliance/Signer.puml
!includeurl AWSPuml/SecurityIdentityCompliance/VerifiedPermissions.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAF.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAFBadBot.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAFBot.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAFBotControl.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAFFilteringRule.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAFLabels.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAFManagedRule.puml
!includeurl AWSPuml/SecurityIdentityCompliance/WAFRule.puml
!includeurl AWSPuml/Serverless/all.puml
!includeurl AWSPuml/Serverless/Serverless.puml
!includeurl AWSPuml/Storage/all.puml
!includeurl AWSPuml/Storage/Backup.puml
!includeurl AWSPuml/Storage/BackupAWSBackupforAWSCloudFormation.puml
!includeurl AWSPuml/Storage/BackupAWSBackupsupportforAmazonFSxforNetAppONTAP.puml
!includeurl AWSPuml/Storage/BackupAWSBackupsupportforAmazonS3.puml
!includeurl AWSPuml/Storage/BackupAWSBackupsupportforVMwareWorkloads.puml
!includeurl AWSPuml/Storage/BackupAuditManager.puml
!includeurl AWSPuml/Storage/BackupBackupPlan.puml
!includeurl AWSPuml/Storage/BackupBackupRestore.puml
!includeurl AWSPuml/Storage/BackupBackupVault.puml
!includeurl AWSPuml/Storage/BackupComplianceReporting.puml
!includeurl AWSPuml/Storage/BackupCompute.puml
!includeurl AWSPuml/Storage/BackupDatabase.puml
!includeurl AWSPuml/Storage/BackupGateway.puml
!includeurl AWSPuml/Storage/BackupLegalHold.puml
!includeurl AWSPuml/Storage/BackupRecoveryPointObjective.puml
!includeurl AWSPuml/Storage/BackupRecoveryTimeObjective.puml
!includeurl AWSPuml/Storage/BackupStorage.puml
!includeurl AWSPuml/Storage/BackupVaultLock.puml
!includeurl AWSPuml/Storage/BackupVirtualMachine.puml
!includeurl AWSPuml/Storage/BackupVirtualMachineMonitor.puml
!includeurl AWSPuml/Storage/EFS.puml
!includeurl AWSPuml/Storage/ElasticBlockStore.puml
!includeurl AWSPuml/Storage/ElasticBlockStoreAmazonDataLifecycleManager.puml
!includeurl AWSPuml/Storage/ElasticBlockStoreMultipleVolumes.puml
!includeurl AWSPuml/Storage/ElasticBlockStoreSnapshot.puml
!includeurl AWSPuml/Storage/ElasticBlockStoreVolume.puml
!includeurl AWSPuml/Storage/ElasticBlockStoreVolumegp3.puml
!includeurl AWSPuml/Storage/ElasticDisasterRecovery.puml
!includeurl AWSPuml/Storage/ElasticFileSystemElasticThroughput.puml
!includeurl AWSPuml/Storage/ElasticFileSystemFileSystem.puml
!includeurl AWSPuml/Storage/ElasticFileSystemIntelligentTiering.puml
!includeurl AWSPuml/Storage/ElasticFileSystemOneZone.puml
!includeurl AWSPuml/Storage/ElasticFileSystemOneZoneInfrequentAccess.puml
!includeurl AWSPuml/Storage/ElasticFileSystemStandard.puml
!includeurl AWSPuml/Storage/ElasticFileSystemStandardInfrequentAccess.puml
!includeurl AWSPuml/Storage/FSx.puml
!includeurl AWSPuml/Storage/FSxforLustre.puml
!includeurl AWSPuml/Storage/FSxforNetAppONTAP.puml
!includeurl AWSPuml/Storage/FSxforOpenZFS.puml
!includeurl AWSPuml/Storage/FSxforWFS.puml
!includeurl AWSPuml/Storage/FileCache.puml
!includeurl AWSPuml/Storage/FileCacheHybridNFSlinkeddatasets.puml
!includeurl AWSPuml/Storage/FileCacheOnpremisesNFSlinkeddatasets.puml
!includeurl AWSPuml/Storage/FileCacheS3linkeddatasets.puml
!includeurl AWSPuml/Storage/S3onOutposts.puml
!includeurl AWSPuml/Storage/SimpleStorageService.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceBucket.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceBucketWithObjects.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceDirectoryBucket.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceGeneralAccessPoints.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceGlacier.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceGlacierArchive.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceGlacierVault.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceObject.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3BatchOperations.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3ExpressOneZone.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3GlacierDeepArchive.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3GlacierFlexibleRetrieval.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3GlacierInstantRetrieval.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3IntelligentTiering.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3MultiRegionAccessPoints.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3ObjectLambda.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3ObjectLambdaAccessPoints.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3ObjectLock.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3OnOutposts.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3OneZoneIA.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3Replication.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3ReplicationTimeControl.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3Select.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3Standard.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3StandardIA.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3StorageLens.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceVPCAccessPoints.puml
!includeurl AWSPuml/Storage/Snowball.puml
!includeurl AWSPuml/Storage/SnowballEdge.puml
!includeurl AWSPuml/Storage/SnowballSnowballImportExport.puml
!includeurl AWSPuml/Storage/Snowcone.puml
!includeurl AWSPuml/Storage/Storage.puml
!includeurl AWSPuml/Storage/StorageGateway.puml
!includeurl AWSPuml/Storage/StorageGatewayAmazonFSxFileGateway.puml
!includeurl AWSPuml/Storage/StorageGatewayAmazonS3FileGateway.puml
!includeurl AWSPuml/Storage/StorageGatewayCachedVolume.puml
!includeurl AWSPuml/Storage/StorageGatewayFileGateway.puml
!includeurl AWSPuml/Storage/StorageGatewayNoncachedVolume.puml
!includeurl AWSPuml/Storage/StorageGatewayTapeGateway.puml
!includeurl AWSPuml/Storage/StorageGatewayVirtualTapeLibrary.puml
!includeurl AWSPuml/Storage/StorageGatewayVolumeGateway.puml
