' GCP icon macros. They all accept (e_alias, e_label, e_techn). Prefer including GCPPuml/[CATEGORY]/all.puml. Always include GCPPuml/GCPCommon.puml

!define GCPPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/refs/heads/master/dist
!includeurl GCPPuml/AI_and_Machine_Learning/all.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AI_Hub.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AI_Platform.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AI_Platform_Data_Labeling_Service.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Advanced_Solutions_Lab.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AutoML_Natural_Language.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AutoML_Tables.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AutoML_Translation.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AutoML_Video_Intelligence.puml
!includeurl GCPPuml/AI_and_Machine_Learning/AutoML_Vision.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_AutoML.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Inference_API.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Jobs_API.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Natural_Language_API.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Speech_to_Text.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_TPU.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Text_to_Speech.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Translation_API.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Video_Intelligence_API.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Cloud_Vision_API.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Dialog_Flow_Enterprise_Edition.puml
!includeurl GCPPuml/AI_and_Machine_Learning/Recommendations_AI.puml
!includeurl GCPPuml/API_Management/all.puml
!includeurl GCPPuml/API_Management/API_Analytics.puml
!includeurl GCPPuml/API_Management/API_Monetization.puml
!includeurl GCPPuml/API_Management/Apigee_API_Platform.puml
!includeurl GCPPuml/API_Management/Apigee_Sense.puml
!includeurl GCPPuml/API_Management/Cloud_Endpoints.puml
!includeurl GCPPuml/API_Management/Developer_Portal.puml
!includeurl GCPPuml/Compute/all.puml
!includeurl GCPPuml/Compute/App_Engine.puml
!includeurl GCPPuml/Compute/Cloud_Functions.puml
!includeurl GCPPuml/Compute/Cloud_Run.puml
!includeurl GCPPuml/Compute/Compute_Engine.puml
!includeurl GCPPuml/Compute/Container_Optimized_OS.puml
!includeurl GCPPuml/Compute/GKE_On_Prem.puml
!includeurl GCPPuml/Compute/GPU.puml
!includeurl GCPPuml/Compute/Kubernetes_Engine.puml
!includeurl GCPPuml/Data_Analytics/all.puml
!includeurl GCPPuml/Data_Analytics/BigQuery.puml
!includeurl GCPPuml/Data_Analytics/Cloud_Composer.puml
!includeurl GCPPuml/Data_Analytics/Cloud_Data_Catalog.puml
!includeurl GCPPuml/Data_Analytics/Cloud_Data_Fusion.puml
!includeurl GCPPuml/Data_Analytics/Cloud_Dataflow.puml
!includeurl GCPPuml/Data_Analytics/Cloud_Datalab.puml
!includeurl GCPPuml/Data_Analytics/Cloud_Dataprep.puml
!includeurl GCPPuml/Data_Analytics/Cloud_Dataproc.puml
!includeurl GCPPuml/Data_Analytics/Cloud_PubSub.puml
!includeurl GCPPuml/Data_Analytics/Genomics.puml
!includeurl GCPPuml/Databases/all.puml
!includeurl GCPPuml/Databases/Cloud_Bigtable.puml
!includeurl GCPPuml/Databases/Cloud_Datastore.puml
!includeurl GCPPuml/Databases/Cloud_Firestore.puml
!includeurl GCPPuml/Databases/Cloud_Memorystore.puml
!includeurl GCPPuml/Databases/Cloud_SQL.puml
!includeurl GCPPuml/Databases/Cloud_Spanner.puml
!includeurl GCPPuml/Developer_Tools/all.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Build.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Code.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Code_for_IntelliJ.puml
!includeurl GCPPuml/Developer_Tools/Cloud_SDK.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Scheduler.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Source_Repositories.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Tasks.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Test_Lab.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Tools_for_Eclipse.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Tools_for_PowerShell.puml
!includeurl GCPPuml/Developer_Tools/Cloud_Tools_for_Visual_Studio.puml
!includeurl GCPPuml/Developer_Tools/Container_Registry.puml
!includeurl GCPPuml/Developer_Tools/Gradle_App_Engine_Plugin.puml
!includeurl GCPPuml/Developer_Tools/IDE_Plugins.puml
!includeurl GCPPuml/Developer_Tools/Maven_App_Engine_Plugin.puml
!includeurl GCPPuml/Hybrid_and_Multi_Cloud/all.puml
!includeurl GCPPuml/Hybrid_and_Multi_Cloud/Stackdriver.puml
!includeurl GCPPuml/Hybrid_and_Multi_Cloud/Traffic_Director.puml
!includeurl GCPPuml/Internet_of_Things/all.puml
!includeurl GCPPuml/Internet_of_Things/Cloud_IoT_Core.puml
!includeurl GCPPuml/Management_Tools/all.puml
!includeurl GCPPuml/Management_Tools/Cloud_APIs.puml
!includeurl GCPPuml/Management_Tools/Cloud_Billing_API.puml
!includeurl GCPPuml/Management_Tools/Cloud_Console.puml
!includeurl GCPPuml/Management_Tools/Cloud_Deployment_Manager.puml
!includeurl GCPPuml/Management_Tools/Cloud_Mobile_App.puml
!includeurl GCPPuml/Management_Tools/Cloud_Service_Mesh.puml
!includeurl GCPPuml/Management_Tools/Cloud_Shell.puml
!includeurl GCPPuml/Management_Tools/Debugger.puml
!includeurl GCPPuml/Management_Tools/Error_Reporting.puml
!includeurl GCPPuml/Management_Tools/Logging.puml
!includeurl GCPPuml/Management_Tools/Monitoring.puml
!includeurl GCPPuml/Management_Tools/Profiler.puml
!includeurl GCPPuml/Management_Tools/Stackdriver.puml
!includeurl GCPPuml/Management_Tools/Trace.puml
!includeurl GCPPuml/Migration/all.puml
!includeurl GCPPuml/Migration/Transfer_Appliance.puml
!includeurl GCPPuml/Networking/all.puml
!includeurl GCPPuml/Networking/Cloud_Armor.puml
!includeurl GCPPuml/Networking/Cloud_CDN.puml
!includeurl GCPPuml/Networking/Cloud_DNS.puml
!includeurl GCPPuml/Networking/Cloud_External_IP_Addresses.puml
!includeurl GCPPuml/Networking/Cloud_Firewall_Rules.puml
!includeurl GCPPuml/Networking/Cloud_Load_Balancing.puml
!includeurl GCPPuml/Networking/Cloud_NAT.puml
!includeurl GCPPuml/Networking/Cloud_Network.puml
!includeurl GCPPuml/Networking/Cloud_Router.puml
!includeurl GCPPuml/Networking/Cloud_Routes.puml
!includeurl GCPPuml/Networking/Cloud_VPN.puml
!includeurl GCPPuml/Networking/Dedicated_Interconnect.puml
!includeurl GCPPuml/Networking/Partner_Interconnect.puml
!includeurl GCPPuml/Networking/Premium_Network_Tier.puml
!includeurl GCPPuml/Networking/Standard_Network_Tier.puml
!includeurl GCPPuml/Networking/Traffic_Director.puml
!includeurl GCPPuml/Networking/Virtual_Private_Cloud.puml
!includeurl GCPPuml/Security/all.puml
!includeurl GCPPuml/Security/Cloud_IAM.puml
!includeurl GCPPuml/Security/Cloud_Resource_Manager.puml
!includeurl GCPPuml/Security/Cloud_Security_Command_Center.puml
!includeurl GCPPuml/Security/Cloud_Security_Scanner.puml
!includeurl GCPPuml/Security/Key_Management_Service.puml
!includeurl GCPPuml/Storage/all.puml
!includeurl GCPPuml/Storage/Cloud_Filestore.puml
!includeurl GCPPuml/Storage/Cloud_Storage.puml
!includeurl GCPPuml/Storage/Persistent_Disk.puml
