name: Release PlantUML icons prompt

# Run on push to main or manual trigger
on:
  # Run when pushed. Use { branches: [main, master] } to run only on specific branches
  push:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # OPTIONAL: Run at a specific cron schedule, e.g. first day of every month at 12:00 UTC (noon)
  schedule:
    - cron: "0 12 1 * *"

# Allow writing releases and assets
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate PUML files
        run: |
          echo "' AWS icon macros. They all accept (e_alias, e_label, e_techn). Prefer including AWSPuml/[CATEGORY]/all.puml" > AWS.puml
          echo '!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/refs/heads/main/dist' >> AWS.puml
          curl https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/refs/heads/main/AWSSymbols.md \
            | grep -Po '\b[\w./-]+\.puml\b' \
            | sed 's/^/!includeurl AWSPuml\//' \
            >> AWS.puml

          echo "' Azure icon macros. They all accept (e_alias, e_label, e_techn). Prefer including AzurePuml/[CATEGORY]/all.puml. Always include AzurePuml/AzureCommon.puml
          " > Azure.puml
          echo '!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist' >> Azure.puml
          curl https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/refs/heads/master/AzureSymbols.md \
            | grep -Po '\b[\w./-]+\.puml\b' \
            | grep -v 'AzurePuml/' \
            | sed 's/^/!includeurl AzurePuml\//' \
            >> Azure.puml

          echo "' GCP icon macros. They all accept (e_alias, e_label, e_techn). Prefer including GCPPuml/[CATEGORY]/all.puml. Always include GCPPuml/GCPCommon.puml
          " > GCP.puml
          echo '!define GCPPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/refs/heads/master/dist' >> GCP.puml
          curl https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/refs/heads/master/Symbols.md \
            | grep -Po '\b[\w./-]+\.puml\b' \
            | sed 's/^/!includeurl GCPPuml\//' \
            >> GCP.puml

      - name: Release PUML files
        uses: ncipollo/release-action@v1
        with:
          tag: plantuml
          name: plantuml
          allowUpdates: true
          replacesArtifacts: true
          artifacts: |
            AWS.puml
            Azure.puml
            GCP.puml
